#!/sbin/sh
# Sourced by update-binary during flash.

ui_print ""
ui_print "=============================="
ui_print "  Privacy & Degoogle v1.5.0"
ui_print "  Z Flip 4 / One UI 7"
ui_print "=============================="
ui_print ""
ui_print "Installs: Privacy Settings app (standalone, not a launcher)"
ui_print ""
ui_print "What it does:"
ui_print "  Open the app from your launcher after reboot."
ui_print "  Tap buttons to disable Samsung and Google bloat one by one,"
ui_print "  or hit Disable All to nuke an entire section at once."
ui_print "  Toggles in the Hardening section apply instantly with root."
ui_print ""
ui_print "Boot log: /sdcard/Download/plasma-theme.log"
ui_print ""
ui_print "Reboot to apply."
ui_print ""
